# Generated by Django 4.2.7 on 2025-10-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_scheduledmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=200, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['source_name'],
            },
        ),
    ]
