# Generated by Django 4.2.7 on 2025-10-09 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_property_zohoconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('site_visit', 'Site Visit'), ('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('dead', 'Dead'), ('converted', 'Converted')], max_length=50, unique=True)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('site_visit', 'Site Visit'), ('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('dead', 'Dead'), ('converted', 'Converted')], default='new', max_length=50),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Sales Director - T1', 'Sales Director - T1'), ('TEAM Head - T2', 'TEAM Head - T2'), ('Team leader - t3', 'Team leader - t3'), ('Sales Manager - T4', 'Sales Manager - T4'), ('Sales Executive - T5', 'Sales Executive - T5'), ('Telecaller - T6', 'Telecaller - T6'), ('BROKER', 'BROKER'), ('Commercial', 'Commercial')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='leads.teammember')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.teammember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('sla_deadline', models.DateTimeField()),
                ('is_attended', models.BooleanField(default=False)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_leads', to='leads.teammember')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='leads.lead')),
            ],
        ),
    ]
