# Generated by Django 4.2.7 on 2025-10-14 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='project_brochures/'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='leads.project')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
