# Generated by Django 4.2.7 on 2025-10-14 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_project_brochure_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('DOCUMENT', 'Document')], default='TEXT', max_length=20)),
                ('message_text', models.TextField()),
                ('api_key', models.TextField()),
                ('campaign_name', models.CharField(max_length=100)),
                ('is_drip_message', models.BooleanField(default=False)),
                ('drip_delay_minutes', models.IntegerField(default=30)),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='leads.project')),
            ],
            options={
                'ordering': ['project', 'order'],
            },
        ),
    ]
