# Generated by Django 4.2.7 on 2025-10-16 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_whatsappcampaign_whatsapptemplate_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_type', models.CharField(choices=[('form_submission', 'Form Submission'), ('whatsapp_message', 'WhatsApp Message'), ('whatsapp_campaign', 'WhatsApp Campaign'), ('phone_call', 'Phone Call'), ('email_sent', 'Email Sent'), ('status_change', 'Status Change'), ('assignment', 'Lead Assignment'), ('note_added', 'Note Added')], max_length=50)),
                ('source_type', models.CharField(choices=[('meta', 'Meta Leads'), ('google', 'Google Leads'), ('ivr', 'IVR Calls'), ('manual', 'Manual Entry')], default='manual', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicatePhoneTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('ivr_calls', models.JSONField(blank=True, default=list)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('google_leads', models.ManyToManyField(blank=True, related_name='google_duplicates', to='leads.lead')),
                ('meta_leads', models.ManyToManyField(blank=True, related_name='meta_duplicates', to='leads.lead')),
            ],
        ),
    ]
