# Generated by Django 4.2.7 on 2025-10-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_assignment_tracking'),
        ('leads', '0012_leadjourney_duplicatephonetracker'),
    ]

    operations = [
    ]
