# Generated by Django 4.2.7 on 2025-10-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_merge_20251016_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='List of amenities available'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Project description and details'),
        ),
    ]
