# Generated by Django 4.2.7 on 2025-11-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_leadviewactivity_leadreassignmentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0.8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='leads.lead')),
            ],
            options={
                'ordering': ['-confidence', '-created_at'],
                'unique_together': {('lead', 'tag')},
            },
        ),
    ]
