# Generated by Django 4.2.7 on 2025-11-13 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_leadrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ever_interested',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LeadInterestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_interested_at', models.DateTimeField(auto_now_add=True)),
                ('stage_at_time', models.CharField(max_length=50)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_logs', to='leads.lead')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.teammember')),
            ],
            options={
                'ordering': ['-marked_interested_at'],
            },
        ),
    ]
