# Generated by Django 4.2.7 on 2025-11-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_alter_callrecord_options_remove_callrecord_call_id_and_more'),
        ('leads', '0024_clickapikey_alter_callrecord_acefone_call_id_and_more'),
    ]

    operations = [
    ]
