# Generated by Django 4.2.7 on 2025-11-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_add_sync_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('initiated', 'Call Initiated'), ('connected', 'Call Connected'), ('failed', 'Call Failed'), ('no_answer', 'No Answer')], default='initiated', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.teammember')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoCallConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text="Project name to trigger calls for (e.g., 'Chrysalis')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapped_agent', models.ForeignKey(help_text='Agent to receive calls', on_delete=django.db.models.deletion.CASCADE, to='leads.teammember')),
            ],
            options={
                'unique_together': {('project_name', 'mapped_agent')},
            },
        ),
    ]
