# Generated by Django 4.2.7 on 2025-11-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_add_auto_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.teammember')),
            ],
            options={
                'ordering': ['scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('call_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('bulk', 'Bulk')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.teammember')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
    ]
