# Generated by Django 4.2.7 on 2025-11-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_scheduledcall_calllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitedNetworkBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=50)),
                ('booking_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_address', models.TextField(blank=True)),
                ('nominee_name', models.CharField(blank=True, max_length=200)),
                ('unit_type', models.CharField(max_length=50)),
                ('unit_number', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('project_name', models.CharField(max_length=200)),
                ('project_location', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('cp_code', models.CharField(blank=True, max_length=50)),
                ('cp_company', models.CharField(blank=True, max_length=200)),
                ('cp_name', models.CharField(blank=True, max_length=200)),
                ('cp_phone', models.CharField(blank=True, max_length=20)),
                ('cp_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(max_length=50)),
                ('booking_source', models.CharField(default='web_form', max_length=50)),
                ('created_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'United Network Booking',
                'verbose_name_plural': 'United Network Bookings',
                'ordering': ['-received_at'],
            },
        ),
    ]
