# Generated by Django 4.2.7 on 2025-12-01 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_unitednetworkbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallKaroAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_team_member', models.ForeignKey(blank=True, help_text='Team member this agent is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.teammember')),
            ],
            options={
                'verbose_name': 'Call Karo Agent',
                'verbose_name_plural': 'Call Karo Agents',
            },
        ),
        migrations.CreateModel(
            name='CallKaroConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Call Karo AI API Key', max_length=255)),
                ('default_agent_id', models.CharField(help_text='Default AI Agent ID', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Call Karo Configuration',
                'verbose_name_plural': 'Call Karo Configurations',
            },
        ),
        migrations.CreateModel(
            name='CallKaroCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('total_calls', models.IntegerField(default=0)),
                ('completed_calls', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.callkaroagent')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.teammember')),
            ],
            options={
                'verbose_name': 'Call Karo Campaign',
                'verbose_name_plural': 'Call Karo Campaigns',
            },
        ),
        migrations.CreateModel(
            name='CallKaroCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('answered', 'Answered'), ('completed', 'Completed'), ('failed', 'Failed'), ('missed', 'Missed'), ('busy', 'Busy'), ('no_answer', 'No Answer')], default='initiated', max_length=20)),
                ('duration', models.IntegerField(blank=True, help_text='Call duration in seconds', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('min_trigger_time', models.TimeField(blank=True, null=True)),
                ('max_trigger_time', models.TimeField(blank=True, null=True)),
                ('carry_over', models.BooleanField(default=False)),
                ('number_of_retries', models.IntegerField(default=0)),
                ('gap_between_retries', models.JSONField(blank=True, default=list)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.callkaroagent')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.callkarocampaign')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.teammember')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
            options={
                'verbose_name': 'Call Karo Call Log',
                'verbose_name_plural': 'Call Karo Call Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
