# Generated by Django 4.2.7 on 2025-12-04 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_add_callkaro_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DripCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_subscribers', models.IntegerField(default=0)),
                ('total_messages_sent', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drip_campaigns', to='leads.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DripMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(help_text='Day number in the sequence (1, 2, 3, etc.)')),
                ('template_name', models.CharField(help_text='AI Sensy template name', max_length=100)),
                ('campaign_name', models.CharField(help_text='AI Sensy campaign name', max_length=100)),
                ('message_text', models.TextField()),
                ('api_key', models.TextField()),
                ('template_params', models.JSONField(default=list, help_text='Template parameters for AI Sensy')),
                ('fallback_params', models.JSONField(default=dict, help_text='Fallback parameter values')),
                ('delay_hours', models.IntegerField(default=24, help_text='Hours to wait before sending this message')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leads.dripcampaign')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('campaign', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='DripSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('unsubscribed', 'Unsubscribed')], default='active', max_length=20)),
                ('current_day', models.IntegerField(default=0, help_text='Current day in the sequence')),
                ('next_message_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='leads.dripcampaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drip_subscriptions', to='leads.lead')),
            ],
            options={
                'ordering': ['-subscribed_at'],
                'unique_together': {('campaign', 'lead')},
            },
        ),
        migrations.CreateModel(
            name='DripMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=100)),
                ('final_message_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drip_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='leads.dripmessage')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='leads.dripsubscriber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
