# Generated by Django 4.2.7 on 2025-12-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_add_drip_campaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='dripmessage',
            name='delay_minutes',
            field=models.IntegerField(default=0, help_text='Additional minutes to wait'),
        ),
    ]
