# Generated by Django 4.2.7 on 2025-12-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_form_source_mapping'),
        ('leads', '0033_add_delay_minutes'),
    ]

    operations = [
    ]
