# Generated by Django 4.2.7 on 2025-12-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0037_bulk_call_agent_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='call_sid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bulkcallrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('calling', 'Calling'), ('connected', 'Connected'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('skipped', 'Skipped (Duplicate)')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('bulk', 'Bulk'), ('auto_daily', 'Auto Daily')], max_length=20),
        ),
    ]
