# Generated by Django 4.2.7 on 2026-01-07 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0039_call_report_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='callkaroagent',
            name='agent_type',
            field=models.CharField(choices=[('general', 'General Purpose'), ('lead_qualification', 'Lead Qualification'), ('project_specific', 'Project Specific'), ('follow_up', 'Follow Up')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='callkaroagent',
            name='project_name',
            field=models.CharField(blank=True, help_text='For project-specific agents', max_length=200),
        ),
        migrations.AddField(
            model_name='unitednetworkbooking',
            name='custom_source',
            field=models.CharField(blank=True, help_text='Custom source if not in predefined list', max_length=100),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.CreateModel(
            name='BookingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='leads.bookingsourcecategory')),
            ],
            options={
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='unitednetworkbooking',
            name='source_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.bookingsourcecategory'),
        ),
        migrations.AddField(
            model_name='unitednetworkbooking',
            name='source_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.bookingsource'),
        ),
    ]
