# Generated by Django 4.2.7 on 2026-01-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_clickapikey_alter_callrecord_acefone_call_id_and_more'),
        ('leads', '0044_add_campaign_variants'),
    ]

    operations = [
    ]
