# Generated by Django 4.2.7 on 2026-01-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0047_ai_agent_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aicalllog',
            new_name='leads_aical_lead_id_9501ba_idx',
            old_name='leads_aical_lead_id_b8c9e5_idx',
        ),
        migrations.RenameIndex(
            model_name='aicalllog',
            new_name='leads_aical_phone_n_069157_idx',
            old_name='leads_aical_phone_n_a7f2d1_idx',
        ),
    ]
