# Generated by Django 4.2.7 on 2025-10-11 09:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_leadstage_lead_stage_teammember_leadnote_and_more'),
        ('tata_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TataDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ring_strategy', models.CharField(blank=True, max_length=50)),
                ('agent_count', models.IntegerField(default=0)),
                ('calls_answered', models.IntegerField(default=0)),
                ('calls_missed', models.IntegerField(default=0)),
                ('use_as_queue', models.BooleanField(default=False)),
                ('queue_timeout', models.IntegerField(default=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TataRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('music_on_hold', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tatacall',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='callnote',
            name='agent_disposition',
        ),
        migrations.AlterField(
            model_name='callnote',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tata_integration.tatacall'),
        ),
        migrations.AlterField(
            model_name='tatacall',
            name='agent_name',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tatacall',
            name='agent_number',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tatacall',
            name='direction',
            field=models.CharField(default='inbound', max_length=20),
        ),
        migrations.AlterField(
            model_name='tatacall',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='tatacall',
            name='recording_url',
            field=models.URLField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tatacall',
            name='status',
            field=models.CharField(default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='tatacall',
            name='uuid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='TataAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('extension_id', models.CharField(blank=True, max_length=50)),
                ('timeout', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tata_integration.tatadepartment')),
            ],
        ),
    ]
