# Generated by Django 4.2.7 on 2025-10-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tata_integration', '0002_tatadepartment_tatarecording_alter_tatacall_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatacall',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
