from django.urls import path
from django.shortcuts import render
from . import views, project_views, whatsapp_views, enhanced_views, team_views, reassignment_views, team_auth, analytics_views, hrms_views, activity_views, ai_views, call_views, acefone_views, simple_callkaro, auto_sync_views, auto_sync_control_view, integration_views, sync_dashboard_views, auto_call_views, views_bop, bulk_call_views, enhanced_sync_views, booking_views, api_views, project_team_views
from . import drip_campaign_views as drip_views
from .sync_campaigns_view import sync_campaigns_data
from .bulk_whatsapp_views import project_bulk_whatsapp, send_bulk_whatsapp
from . import form_mapping_views, auto_whatsapp_views, bulk_call_upload_views, callkaro_admin_views, google_sheets_views, call_analytics_views, call_report_views, call_history_views, booking_source_views
from django.shortcuts import render

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('dashboard/', views.dashboard, name='dashboard_explicit'),
    path('leads/', views.leads_list, name='leads_list'),
    path('meta-leads/', views.meta_leads, name='meta_leads'),
    path('google-leads/', views.google_leads, name='google_leads'),
    path('leads/<int:lead_id>/', views.lead_detail, name='lead_detail'),
    path('leads/<int:lead_id>/calls/', views.lead_calls, name='lead_calls'),
    path('sync/', views.sync_leads, name='sync_leads'),
    path('whatsapp/', views.whatsapp_page, name='whatsapp_page'),
    path('send-whatsapp/', views.send_whatsapp, name='send_whatsapp'),
    path('add-lead/', views.add_lead, name='add_lead'),
    path('export/', views.export_leads, name='export_leads'),
    path('webhook/google-leads/', views.google_leads_webhook, name='google_leads_webhook'),
    path('test-google/', views.test_google_webhook, name='test_google_webhook'),
    path('import-google-leads/', views.import_google_sheet_leads, name='import_google_leads'),
    path('sync-google-sheet/', views.sync_google_sheet, name='sync_google_sheet'),
    path('refresh-google-leads/', views.refresh_google_leads, name='refresh_google_leads'),
    path('sheet-config/', views.sheet_config, name='sheet_config'),
    path('save-sheet-config/', views.save_sheet_config, name='save_sheet_config'),
    path('test-sheet-connection/', views.test_sheet_connection, name='test_sheet_connection'),

    path('debug-leads/', views.debug_leads, name='debug_leads'),
    path('schedule-whatsapp/', views.schedule_whatsapp, name='schedule_whatsapp'),
    path('process-scheduled/', views.process_scheduled_messages, name='process_scheduled'),
    path('check-scheduled/', views.check_scheduled_messages, name='check_scheduled'),
    path('auto-process/', views.auto_process_scheduled, name='auto_process'),
    path('scheduled-messages/', views.scheduled_messages_page, name='scheduled_messages'),
    path('source-mapping/', views.source_mapping_page, name='source_mapping'),
    path('save-source-mapping/', views.save_source_mapping, name='save_source_mapping'),
    path('auto-sync-status/', views.auto_sync_status, name='auto_sync_status'),
    path('zoho-config/', views.zoho_config_page, name='zoho_config'),
    path('save-zoho-config/', views.save_zoho_config, name='save_zoho_config'),
    path('zoho-auth/', views.zoho_auth, name='zoho_auth'),
    path('zoho-callback/', views.zoho_callback, name='zoho_callback'),
    path('reset-zoho-config/', views.reset_zoho_config, name='reset_zoho_config'),
    path('zoho-status/', views.zoho_status_page, name='zoho_status'),
    path('test-zoho-connection/', views.test_zoho_connection, name='test_zoho_connection'),
    path('sync-lead-to-zoho/', views.sync_lead_to_zoho, name='sync_lead_to_zoho'),
    path('refresh-zoho-token/', views.refresh_zoho_token_endpoint, name='refresh_zoho_token'),
    path('properties/', views.properties_page, name='properties'),
    path('property-mapping/', views.property_mapping_page, name='property_mapping'),
    # Team management URLs
    path('team/', team_views.team_members_list, name='team_members'),
    path('team/hierarchy/', team_views.team_hierarchy_view, name='team_hierarchy'),
    path('team/assign/', team_views.assign_team_member, name='assign_team_member'),
    path('team/auto-assign/', team_views.auto_assign_hierarchy, name='auto_assign_hierarchy'),
    path('team/create/', team_views.create_team_member, name='create_team_member'),
    path('team/<int:member_id>/suggestions/', team_views.team_member_suggestions, name='team_member_suggestions'),
    path('assign-lead/', views.assign_lead, name='assign_lead'),
    path('update-stage/', views.update_lead_stage, name='update_lead_stage'),
    path('add-note/', views.add_lead_note, name='add_lead_note'),
    path('my-leads/', views.my_leads, name='my_leads'),
    # Lead reassignment URLs
    path('leads/overdue/', reassignment_views.overdue_leads_dashboard, name='overdue_leads_dashboard'),
    path('leads/shuffle-overdue/', reassignment_views.shuffle_overdue_leads, name='shuffle_overdue_leads'),
    path('leads/reassign-single/', reassignment_views.reassign_single_lead, name='reassign_single_lead'),
    path('leads/<int:lead_id>/assignment-timeline/', reassignment_views.lead_assignment_timeline, name='lead_assignment_timeline'),
    path('leads/initialize-round-robin/', reassignment_views.initialize_round_robin, name='initialize_round_robin'),
    # Team member authentication URLs
    path('team/login/', team_auth.team_login_view, name='team_login'),
    path('team/logout/', team_auth.team_logout_view, name='team_logout'),
    path('team/dashboard/', team_auth.team_dashboard_view, name='team_dashboard'),
    path('team/profile/', team_auth.team_profile_view, name='team_profile'),
    path('team/leads/<int:lead_id>/', team_auth.team_lead_detail_view, name='team_lead_detail'),
    path('team/update-status/', team_auth.team_update_lead_status, name='team_update_status'),
    path('team/add-note/', team_auth.team_add_note, name='team_add_note'),
    # Projects URLs
    path('projects/', project_views.projects_list, name='projects_list'),
    path('projects/create/', project_views.project_create, name='project_create'),
    path('projects/<int:project_id>/', project_views.project_detail, name='project_detail'),
    path('projects/<int:project_id>/edit/', project_views.project_edit, name='project_edit'),
    path('projects/<int:project_id>/leads/', project_views.project_leads, name='project_leads'),
    path('projects/<int:project_id>/upload-image/', project_views.upload_project_image, name='upload_project_image'),
    path('projects/<int:project_id>/upload-brochure/', project_views.upload_project_brochure, name='upload_project_brochure'),
    path('projects/<int:project_id>/delete-image/<int:image_id>/', project_views.delete_project_image, name='delete_project_image'),
    path('projects/<int:project_id>/delete/', project_views.delete_project, name='delete_project'),
    path('projects/<int:project_id>/bulk-whatsapp/', project_bulk_whatsapp, name='project_bulk_whatsapp'),
    path('projects/<int:project_id>/send-bulk-whatsapp/', send_bulk_whatsapp, name='send_bulk_whatsapp'),
    path('projects/<int:project_id>/start-auto-calling/', project_views.start_auto_calling, name='start_auto_calling'),
    path('projects/<int:project_id>/call-single-lead/', project_views.call_single_lead, name='call_single_lead'),
    path('projects/<int:project_id>/team-members/', project_team_views.project_team_members, name='project_team_members'),
    path('projects/<int:project_id>/upload-team-members/', project_team_views.upload_project_team_members, name='upload_project_team_members'),
    path('projects/<int:project_id>/add-team-member/', project_team_views.add_team_member_to_project, name='add_team_member_to_project'),
    path('projects/<int:project_id>/remove-team-member/<int:team_member_id>/', project_team_views.remove_team_member_from_project, name='remove_team_member_from_project'),
    path('projects/<int:project_id>/whatsapp-templates/', whatsapp_views.project_whatsapp_templates, name='project_whatsapp_templates'),
    path('projects/<int:project_id>/whatsapp-test/', whatsapp_views.project_whatsapp_test, name='project_whatsapp_test'),
    path('whatsapp/test-send/', whatsapp_views.whatsapp_test_send, name='whatsapp_test_send'),
    path('whatsapp/broadcast-to-leads/', whatsapp_views.broadcast_to_project_leads, name='broadcast_to_leads'),
    path('aisensy-sync/', whatsapp_views.aisensy_sync_page, name='aisensy_sync_page'),
    path('add-campaign/', whatsapp_views.add_campaign, name='add_campaign'),
    path('enhanced-leads/', enhanced_views.enhanced_leads_list, name='enhanced_leads'),
    path('whatsapp/sync-aisensy/', whatsapp_views.sync_aisensy_data, name='sync_aisensy'),
    path('whatsapp/test-connection/', whatsapp_views.test_aisensy_connection, name='test_aisensy_connection'),
    path('whatsapp/sync-campaigns/', sync_campaigns_data, name='sync_campaigns'),
    path('send-whatsapp-message/', whatsapp_views.send_whatsapp_message, name='send_whatsapp_message'),
    path('whatsapp/send-message/', whatsapp_views.send_whatsapp_message, name='whatsapp_send_message'),
    path('leads/<int:lead_id>/whatsapp/', whatsapp_views.lead_whatsapp_dashboard, name='lead_whatsapp_dashboard'),
    
    # Analytics URLs
    path('leads-analytics/', analytics_views.leads_analytics, name='leads_analytics'),
    path('new-analytics/', analytics_views.leads_analytics, name='new_analytics'),
    path('call-analytics/', views.call_analytics, name='call_analytics'),
    path('call-analytics/api/', analytics_views.call_analytics_api, name='call_analytics_api'),
    path('call-analytics/sync/', analytics_views.sync_calls_api, name='sync_calls_api'),
    path('call-analytics/by-source/', call_analytics_views.call_analytics_by_source, name='call_analytics_by_source'),
    path('call-analytics/by-source/<int:project_id>/', call_analytics_views.call_analytics_by_source, name='call_analytics_by_source_project'),
    path('call-analytics/report-api/', call_analytics_views.call_report_api, name='call_report_api'),
    path('call-analytics/report-api/<int:project_id>/', call_analytics_views.call_report_api, name='call_report_api_project'),
    path('tata-data/', views.tata_data, name='tata_data'),
    path('leads-analytics/projects-data/', analytics_views.leads_per_project_data, name='leads_per_project_data'),
    path('leads-analytics/day-data/', analytics_views.leads_per_day_data, name='leads_per_day_data'),
    path('leads-analytics/week-data/', analytics_views.leads_per_week_data, name='leads_per_week_data'),
    path('leads-analytics/month-data/', analytics_views.leads_per_month_data, name='leads_per_month_data'),
    
    # Team edit URLs
    path('team/edit/', team_views.edit_team_member, name='edit_team_member'),
    path('team/unassign/', team_views.unassign_team_member, name='unassign_team_member'),
    
    # Missing URLs from sidebar
    path('tagged-leads/', views.tagged_leads, name='tagged_leads'),
    path('ai/', ai_views.ai_dashboard, name='ai_dashboard'),
    path('ai/refresh-insights/', ai_views.refresh_ai_insights, name='refresh_ai_insights'),
    path('interest-analytics/', views.interest_analytics, name='interest_analytics'),
    path('call-panel/', call_views.call_panel, name='call_panel'),
    
    # Auto sync URLs
    path('auto-sync/', auto_sync_control_view.auto_sync_control, name='auto_sync_control'),
    path('start-auto-sync/', auto_sync_views.start_auto_sync, name='start_auto_sync'),
    path('stop-auto-sync/', auto_sync_views.stop_auto_sync, name='stop_auto_sync'),
    path('auto-sync-status-api/', auto_sync_views.auto_sync_status_api, name='auto_sync_status_api'),
    
    # Integration panel URLs (Admin only)
    path('integrations/', integration_views.integration_panel, name='integration_panel'),
    path('integrations/save-meta/', integration_views.save_meta_config, name='save_meta_config'),
    path('integrations/save-google/', integration_views.save_google_config, name='save_google_config'),
    path('integrations/test-meta/', integration_views.test_meta_connection, name='test_meta_connection'),
    path('integrations/test-google/', integration_views.test_google_connection, name='test_google_connection'),
    path('integrations/delete-config/', integration_views.delete_config, name='delete_config'),
    
    # Enhanced sync dashboard URLs
    path('sync-dashboard/', sync_dashboard_views.sync_dashboard, name='sync_dashboard'),
    path('manual-sync-all/', sync_dashboard_views.manual_sync_all, name='manual_sync_all'),
    path('test-sync-button/', sync_dashboard_views.test_sync_button, name='test_sync_button'),
    path('force-sync-now/', sync_dashboard_views.force_sync_now, name='force_sync_now'),
    path('check-missing-leads/', sync_dashboard_views.check_missing_leads, name='check_missing_leads'),
    path('sync-logs-api/', sync_dashboard_views.sync_logs_api, name='sync_logs_api'),
    
    # Auto call URLs
    path('auto-call-config/', auto_call_views.auto_call_config, name='auto_call_config'),
    path('save-auto-call-config/', auto_call_views.save_auto_call_config, name='save_auto_call_config'),
    path('test-auto-call/', auto_call_views.test_auto_call, name='test_auto_call'),
    path('auto-call-logs/', auto_call_views.auto_call_logs, name='auto_call_logs'),
    path('trigger-auto-call/<int:lead_id>/', auto_call_views.trigger_manual_auto_call, name='trigger_manual_auto_call'),
    path('test-bop-sync/<int:lead_id>/', views_bop.test_bop_sync, name='test_bop_sync'),
    
    # Bulk calling URLs
    path('bulk-call-panel/', bulk_call_views.bulk_call_panel, name='bulk_call_panel'),
    path('start-bulk-calling/', bulk_call_views.start_bulk_calling, name='start_bulk_calling'),
    path('handle-scheduled-call/', bulk_call_views.handle_scheduled_call, name='handle_scheduled_call'),
    path('resume-bulk-calling/', bulk_call_views.resume_bulk_calling, name='resume_bulk_calling'),
    path('continue-bulk-calling/', bulk_call_views.continue_bulk_calling, name='continue_bulk_calling'),
    path('check-scheduled-calls/', bulk_call_views.check_scheduled_calls, name='check_scheduled_calls'),
    path('handle-scheduled-interrupt/', bulk_call_views.handle_scheduled_interrupt, name='handle_scheduled_interrupt'),
    path('set-bulk-calling-state/', bulk_call_views.set_bulk_calling_state, name='set_bulk_calling_state'),
    path('ai/analyze-lead/', ai_views.analyze_lead_ai, name='analyze_lead_ai'),
    path('ai/generate-recommendations/', ai_views.generate_ai_recommendations, name='generate_ai_recommendations'),
    path('schedule-callback/', bulk_call_views.schedule_callback, name='schedule_callback'),
    path('test-acefone-api/', bulk_call_views.test_acefone_api, name='test_acefone_api'),
    path('acefone-test-page/', lambda request: render(request, 'leads/test_acefone.html'), name='acefone_test_page'),
    path('daily-sync-analysis/', lambda request: render(request, 'leads/daily_sync_analysis.html'), name='daily_sync_analysis'),
    path('daily-sync-analysis-api/', views.daily_sync_analysis_api, name='daily_sync_analysis_api'),
    path('manual-sync/', lambda request: render(request, 'leads/manual_sync.html'), name='manual_sync'),
    path('date-range-sync/', lambda request: render(request, 'leads/date_range_sync.html'), name='date_range_sync'),
    path('date-range-analysis/', views.date_range_analysis, name='date_range_analysis'),
    path('quick-sync-test/', lambda request: render(request, 'leads/quick_sync_test.html'), name='quick_sync_test'),
    path('check-meta-forms/', views.check_meta_forms, name='check_meta_forms'),
    path('check-todays-leads/', views.check_todays_leads, name='check_todays_leads'),
    path('debug-sync/', lambda request: render(request, 'leads/debug_sync.html'), name='debug_sync'),
    path('sync-gaur-acp/', views.sync_gaur_acp_leads, name='sync_gaur_acp_leads'),
    path('force-sync-now/', sync_dashboard_views.force_sync_now, name='force_sync_now'),
    
    # Call panel API endpoints
    path('dialer-search/', call_views.dialer_search, name='dialer_search'),
    path('initiate-click-call/', call_views.initiate_manual_call, name='initiate_click_call'),
    path('lead-queue-api/', call_views.lead_queue_api, name='lead_queue_api'),
    path('call-stats-api/', call_views.call_stats_api, name='call_stats_api'),
    
    # Simple AI Call
    path('simple-ai-call/', simple_callkaro.simple_ai_call, name='simple_ai_call'),
    path('add-lead/', views.add_lead, name='add_lead'),
    
    # Enhanced Meta Sync URLs (2000+ forms support)
    path('enhanced-sync/dashboard/', enhanced_sync_views.sync_dashboard, name='enhanced_sync_dashboard'),
    path('enhanced-sync/start/', enhanced_sync_views.start_auto_sync, name='enhanced_sync_start'),
    path('enhanced-sync/stop/', enhanced_sync_views.stop_auto_sync, name='enhanced_sync_stop'),
    path('enhanced-sync/status/', enhanced_sync_views.sync_status, name='enhanced_sync_status'),
    path('enhanced-sync/manual/', enhanced_sync_views.manual_sync, name='enhanced_sync_manual'),
    path('enhanced-sync/analytics/', enhanced_sync_views.sync_analytics, name='enhanced_sync_analytics'),
    
    # United Network CRM Booking URLs
    path('webhook/united-network/', booking_views.united_network_webhook, name='united_network_webhook'),
    path('api/booking-webhook/', booking_views.united_network_webhook, name='booking_webhook_alt'),
    path('api/bulk-bookings/', booking_views.united_network_webhook, name='bulk_bookings_alt'),
    path('bookings/', booking_views.bookings_dashboard, name='bookings_dashboard'),
    path('bookings/<int:booking_id>/', booking_views.booking_detail, name='booking_detail'),
    path('bookings/api/', booking_views.bookings_api, name='bookings_api'),
    
    # External API URLs (API Key Authentication)
    path('api/external/status/', api_views.api_status, name='api_status'),
    path('api/external/bookings/', api_views.api_bookings_list, name='api_bookings_list'),
    path('api/external/booking/<str:booking_id>/', api_views.api_booking_detail, name='api_booking_detail'),
    path('api/external/search/', api_views.api_search_bookings, name='api_search_bookings'),
    
    # Missing API endpoints
    path('initiate-call/', views.initiate_call, name='initiate_call'),
    path('generate-message/', views.generate_message, name='generate_message'),
    path('leads/<int:lead_id>/api/', views.lead_detail_api, name='lead_detail_api'),
    path('ai/generate-follow-up/', views.generate_follow_up, name='generate_follow_up'),
    path('acefone-call/', views.acefone_call, name='acefone_call'),
    path('call-console/', lambda request: render(request, 'leads/call_console.html'), name='call_console'),
    path('test-callkaro-agent/', views.test_callkaro_agent, name='test_callkaro_agent'),
    
    # WhatsApp Drip Campaign URLs
    path('drip-campaigns/', drip_views.drip_campaigns_dashboard, name='drip_campaigns_dashboard'),
    path('drip-campaigns/create-gaur-yamuna/', drip_views.create_gaur_yamuna_campaign, name='create_gaur_yamuna_campaign'),
    path('drip-campaigns/<int:campaign_id>/', drip_views.campaign_detail, name='drip_campaign_detail'),
    path('drip-campaigns/subscribe-lead/', drip_views.subscribe_lead_to_drip, name='subscribe_lead_to_drip'),
    path('drip-campaigns/bulk-subscribe/', drip_views.bulk_subscribe_leads, name='bulk_subscribe_leads'),
    path('drip-campaigns/leads-api/', drip_views.leads_api, name='drip_leads_api'),
    path('drip-campaigns/bulk-subscribe-view/', drip_views.bulk_subscribe_view, name='bulk_subscribe_view'),
    path('drip-campaigns/process-pending/', drip_views.process_pending_messages, name='process_pending_messages'),
    path('drip-campaigns/test-message/', drip_views.test_drip_message, name='test_drip_message'),
    path('drip-campaigns/analytics/', drip_views.drip_analytics, name='drip_analytics'),
    path('drip-campaigns/unsubscribe-lead/', drip_views.unsubscribe_lead_from_drip, name='unsubscribe_lead_from_drip'),
    path('drip-campaigns/bulk-unsubscribe/', drip_views.bulk_unsubscribe_leads, name='bulk_unsubscribe_leads'),
    path('drip-campaigns/fix-campaign-names/', drip_views.fix_campaign_names, name='fix_campaign_names'),
    path('drip-campaigns/auto-process/', drip_views.auto_process_drip_messages, name='auto_process_drip_messages'),
    path('drip-campaigns/start-auto-sender/', drip_views.start_auto_sender, name='start_auto_sender'),
    path('drip-campaigns/stop-auto-sender/', drip_views.stop_auto_sender, name='stop_auto_sender'),
    path('drip-campaigns/delete-campaign/', drip_views.delete_campaign, name='delete_campaign'),
    path('drip-campaigns/subscribe-project/', drip_views.subscribe_project_leads, name='subscribe_project_leads'),
    path('drip-campaigns/advance-to-day2/', drip_views.advance_to_day2, name='advance_to_day2'),
    path('drip-campaigns/send-specific-day/', drip_views.send_specific_day_message, name='send_specific_day_message'),
    
    # Form Source Mapping URLs
    path('form-mappings/', form_mapping_views.form_mapping_list, name='form_mapping_list'),
    path('form-mappings/create/', form_mapping_views.create_form_mapping, name='create_form_mapping'),
    path('form-mappings/bulk-create/', form_mapping_views.bulk_create_form_mapping, name='bulk_create_form_mapping'),
    path('form-mappings/<int:mapping_id>/delete/', form_mapping_views.delete_form_mapping, name='delete_form_mapping'),
    path('form-mappings/<int:mapping_id>/toggle/', form_mapping_views.toggle_form_mapping, name='toggle_form_mapping'),
    
    # Auto WhatsApp Campaign URLs
    path('auto-whatsapp/', auto_whatsapp_views.auto_whatsapp_config, name='auto_whatsapp_config'),
    path('auto-whatsapp/create/', auto_whatsapp_views.create_auto_campaign, name='create_auto_campaign'),
    path('auto-whatsapp/<int:campaign_id>/toggle/', auto_whatsapp_views.toggle_auto_campaign, name='toggle_auto_campaign'),
    path('auto-whatsapp/<int:campaign_id>/delete/', auto_whatsapp_views.delete_auto_campaign, name='delete_auto_campaign'),
    path('auto-whatsapp/project-templates/<int:project_id>/', auto_whatsapp_views.get_project_templates, name='get_project_templates'),
    
    # Bulk Call URLs
    path('bulk-call-upload/', bulk_call_upload_views.bulk_call_upload, name='bulk_call_upload'),
    path('bulk-call/upload/', bulk_call_upload_views.process_bulk_call_file, name='process_bulk_call_file'),
    path('bulk-call/<int:campaign_id>/', bulk_call_upload_views.bulk_call_dashboard, name='bulk_call_dashboard'),
    path('bulk-call/<int:campaign_id>/start/', bulk_call_upload_views.start_bulk_calling, name='start_bulk_calling'),
    path('bulk-call/<int:campaign_id>/stop/', bulk_call_upload_views.stop_bulk_calling, name='stop_bulk_calling'),
    path('bulk-call/<int:campaign_id>/resume/', bulk_call_upload_views.resume_bulk_calling, name='resume_bulk_calling'),
    path('bulk-call/<int:campaign_id>/status/', bulk_call_upload_views.bulk_call_status_api, name='bulk_call_status_api'),
    path('bulk-call/<int:campaign_id>/check/', bulk_call_upload_views.campaign_status_check, name='campaign_status_check'),
    path('bulk-call/cleanup/', bulk_call_upload_views.cleanup_campaigns_api, name='cleanup_campaigns_api'),
    path('bulk-call/<int:campaign_id>/delete/', bulk_call_upload_views.delete_bulk_campaign, name='delete_bulk_campaign'),
    path('auto-call/new-leads/', bulk_call_upload_views.auto_call_new_leads, name='auto_call_new_leads'),
    path('auto-call/count/', bulk_call_upload_views.get_new_leads_count, name='get_new_leads_count'),
    path('auto-call/dashboard/', lambda request: render(request, 'leads/auto_call_dashboard.html'), name='auto_call_dashboard'),
    
    # CallKaro Admin URLs
    path('callkaro-agents/', callkaro_admin_views.callkaro_agents_admin, name='callkaro_agents_admin'),
    path('callkaro-agents/add/', callkaro_admin_views.add_callkaro_agent, name='add_callkaro_agent'),
    path('callkaro-config/save/', callkaro_admin_views.save_callkaro_config, name='save_callkaro_config'),
    path('callkaro-agents/<int:agent_id>/delete/', callkaro_admin_views.delete_callkaro_agent, name='delete_callkaro_agent'),
    
    # Google Sheets Integration URLs
    path('google-sheets/', google_sheets_views.google_sheets_dashboard, name='google_sheets_dashboard'),
    path('google-sheets-webhook/', google_sheets_views.google_sheets_webhook, name='google_sheets_webhook'),
    path('add-google-sheet/', google_sheets_views.add_google_sheet, name='add_google_sheet'),
    path('test-google-sheets-webhook/', google_sheets_views.test_google_sheets_webhook, name='test_google_sheets_webhook'),
    path('sync-existing-google-leads/', google_sheets_views.sync_existing_google_leads, name='sync_existing_google_leads'),
    path('sync-individual-sheet/<int:sheet_id>/', google_sheets_views.sync_individual_sheet, name='sync_individual_sheet'),
    path('toggle-sheet-status/<int:sheet_id>/', google_sheets_views.toggle_sheet_status, name='toggle_sheet_status'),
    path('delete-google-sheet/<int:sheet_id>/', google_sheets_views.delete_google_sheet, name='delete_google_sheet'),
    
    # Call Report URLs
    path('call-reports/upload/', call_report_views.call_report_upload_page, name='call_report_upload'),
    path('call-reports/process/', call_report_views.process_call_report_upload, name='process_call_report_upload'),
    path('call-reports/dashboard/', call_report_views.call_report_dashboard, name='call_report_dashboard'),
    path('call-reports/dashboard/<int:upload_id>/', call_report_views.call_report_dashboard, name='call_report_dashboard_detail'),
    path('call-reports/api/', call_report_views.call_report_api, name='call_report_api'),
    path('call-reports/api/<int:upload_id>/', call_report_views.call_report_api, name='call_report_api_detail'),
    path('call-reports/reprocess-matching/', call_report_views.reprocess_call_report_matching, name='reprocess_call_report_matching'),
    
    # Call History URLs
    path('call-history/upload/', call_history_views.call_history_upload, name='call_history_upload'),
    path('call-history/results/', call_history_views.call_history_results, name='call_history_results'),
    path('call-history/save-matches/', call_history_views.save_call_history_matches, name='save_call_history_matches'),
    path('call-history/dashboard/', call_history_views.call_history_dashboard, name='call_history_dashboard'),
    path('call-history/<int:upload_id>/', call_history_views.call_history_detail, name='call_history_detail'),
    
    # Booking Source Management URLs
    path('api/source-categories/', booking_source_views.get_source_categories, name='get_source_categories'),
    path('api/sources/<int:category_id>/', booking_source_views.get_sources_by_category, name='get_sources_by_category'),
    # path('api/sources/create/', booking_source_views.create_custom_source, name='create_custom_source'),`n    path('drip-campaigns/switch-variant/', drip_views.switch_campaign_variant, name='switch_campaign_variant'),`n    path('drip-campaigns/get-variants/', drip_views.get_campaign_variants, name='get_campaign_variants'),`n    path('drip-campaigns/create-spj-10day/', drip_views.create_spj_10day_campaigns, name='create_spj_10day_campaigns'),
    path('drip-campaigns/switch-variant/', drip_views.switch_campaign_variant, name='switch_campaign_variant'),
    path('drip-campaigns/get-variants/', drip_views.get_campaign_variants, name='get_campaign_variants'),
    path('drip-campaigns/create-spj-10day/', drip_views.create_spj_10day_campaigns, name='create_spj_10day_campaigns'),

    path('drip-campaigns/switch-variant/', drip_views.switch_campaign_variant, name='switch_campaign_variant'),
    path('drip-campaigns/get-variants/', drip_views.get_campaign_variants, name='get_campaign_variants'),
    path('drip-campaigns/create-spj-10day/', drip_views.create_spj_10day_campaigns, name='create_spj_10day_campaigns'),


    path('drip-campaigns/switch-variant/', drip_views.switch_campaign_variant, name='switch_campaign_variant'),
    path('drip-campaigns/get-variants/', drip_views.get_campaign_variants, name='get_campaign_variants'),
    path('drip-campaigns/create-spj-10day/', drip_views.create_spj_10day_campaigns, name='create_spj_10day_campaigns'),

    path('drip-campaigns/switch-variant/', drip_views.switch_campaign_variant, name='switch_campaign_variant'),
    path('drip-campaigns/get-variants/', drip_views.get_campaign_variants, name='get_campaign_variants'),
    path('drip-campaigns/create-spj-10day/', drip_views.create_spj_10day_campaigns, name='create_spj_10day_campaigns'),
]